<html xmlns:concordion="http://www.concordion.org/2007/concordion">
<head>
<link href="../../../../concordion.css" rel="stylesheet" type="text/css" />
<title>Fail Fast</title>
</head>
<body>

    <h1>Fail Fast Passthrough</h1>

	<p>
		By default, exceptions are reported but Concordion continues
		processing the rest of the test. With the <code>@FailFast</code> annotation on a test, processing of a test is
		stopped once an exception is encountered.
	</p>

	<p>
		In the case where a test that is annotated with @FailFast calls another test annotated with @FailFast, an exception
		encountered in the lower level test will stop processing of both tests.
	</p>

	<p>
		The following examples use this setup of tests:
	</p>

	<ol>
		<li>
			The lower level test performs two actions:
			it first performs a command that throws an exception and then performs a command that would be successful.
		</li>
		<li>
			The higher level test performs two actions: it first executes the lower level test and then it performs a
			command that would be successfull.
		</li>
	</ol>


	<div class="example">
		<h3>Example - only one test annotated with @FailFast</h3>

		<p>
			<span concordion:execute="#result=simulateRun('NotFailFastRunningFailFast.html')"></span>
			If just the lower level test was annotated with <code>@FailFast</code>, we would expect
			<span concordion:assertEquals="#result.successCount">1</span>
			successful command (from the higher level test) and
			<span concordion:assertEquals="#result.exceptionCount">1</span>
			exception.
		</p>
	</div>

	<div class="example">
		<h3>Example - both annotated with @FailFast</h3>

		<p>
			<span concordion:execute="#result=simulateRun('FailFastRunningFailFast.html')"></span>
			If both tests are annotated with <code>@FailFast</code>, we would expect
			<span concordion:assertEquals="#result.successCount">0</span>
			successful command (from the higher level test) and
			<span concordion:assertEquals="#result.exceptionCount">1</span>
			exception.
		</p>
	</div>

</body>
</html>